version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    command: uvicorn backend.server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    environment:
      - REACT_APP_DEVELOPMENT=false
    ports:
      - "3000:3000"
    depends_on:
      - backend
